FROM golang:1.11

ENV PATH="${GOPATH}/bin:${PATH}"
ENV GOBIN="${GOPATH}/bin"

RUN go get -u github.com/golang/dep/cmd/dep && \
    go get -u gopkg.in/alecthomas/gometalinter.v2 && \
    gometalinter.v2 -i -u

RUN go get github.com/axw/gocov/... && \
	  go get github.com/AlekSi/gocov-xml && \
	  go get -u github.com/jstemmer/go-junit-report

ENTRYPOINT []